spring.application.name=service-inventario
server.port=8084

# Conexión a DB Inventario
spring.datasource.url=jdbc:mysql://localhost:3306/db_inventario?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
