spring.application.name=service-skus
server.port=8083

# Conexión a DB SKUs
spring.datasource.url=jdbc:mysql://localhost:3306/db_skus?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
